// Each puzzle: 5x5 grid, 5 across words, 1 down word at col 2
// All intersections verified: acrossWord[2] === downWord[rowIndex]

export const PUZZLES = [
  {
    id: 1, theme: '🐯 Wildlife',
    grid: [
      ['P','A','T','C','H'],
      ['T','H','I','C','K'],
      ['M','A','G','I','C'],
      ['T','H','E','R','E'],
      ['A','R','R','O','W'],
    ],
    across: [
      { row: 0, clue: 'A mark or wound on skin' },
      { row: 1, clue: 'Dense and solid' },
      { row: 2, clue: 'Sorcery or wizardry' },
      { row: 3, clue: 'That place, not here' },
      { row: 4, clue: 'Shot from a bow' },
    ],
    down: { col: 2, word: 'TIGER', clue: 'Large striped jungle cat 🐯' },
  },
  {
    id: 2, theme: '🌊 Nature',
    grid: [
      ['F','L','O','O','D'],
      ['U','N','C','L','E'],
      ['W','H','E','E','L'],
      ['R','E','A','C','T'],
      ['P','E','N','N','Y'],
    ],
    across: [
      { row: 0, clue: 'A rush of water disaster' },
      { row: 1, clue: "Your parent's brother" },
      { row: 2, clue: 'Round rolling object' },
      { row: 3, clue: 'To respond to something' },
      { row: 4, clue: 'A small coin' },
    ],
    down: { col: 2, word: 'OCEAN', clue: 'Vast body of saltwater 🌊' },
  },
  {
    id: 3, theme: '🚀 Space',
    grid: [
      ['B','A','S','I','N'],
      ['R','I','P','E','N'],
      ['P','E','A','R','L'],
      ['L','U','C','K','Y'],
      ['S','T','E','E','L'],
    ],
    across: [
      { row: 0, clue: 'A bowl-shaped container' },
      { row: 1, clue: 'To become fully mature' },
      { row: 2, clue: 'Gem found inside an oyster' },
      { row: 3, clue: 'Having good fortune' },
      { row: 4, clue: 'Strong grey metal' },
    ],
    down: { col: 2, word: 'SPACE', clue: 'The universe beyond Earth 🚀' },
  },
  {
    id: 4, theme: '💰 Riches',
    grid: [
      ['A','R','M','E','D'],
      ['P','R','O','O','F'],
      ['C','A','N','D','Y'],
      ['B','R','E','E','D'],
      ['R','O','Y','A','L'],
    ],
    across: [
      { row: 0, clue: 'Carrying weapons' },
      { row: 1, clue: 'Evidence that something is true' },
      { row: 2, clue: 'Sweet sugary treat 🍬' },
      { row: 3, clue: 'A type or variety of animal' },
      { row: 4, clue: 'Relating to a king or queen' },
    ],
    down: { col: 2, word: 'MONEY', clue: 'Coins and banknotes 💰' },
  },
  {
    id: 5, theme: '🔥 Elements',
    grid: [
      ['S','O','F','T','Y'],
      ['J','E','L','L','Y'],
      ['C','O','A','T','S'],
      ['G','A','M','E','S'],
      ['C','R','E','E','K'],
    ],
    across: [
      { row: 0, clue: 'A gentle or sensitive person' },
      { row: 1, clue: 'Wobbly sweet spread on toast' },
      { row: 2, clue: 'Outer garments you wear' },
      { row: 3, clue: 'Plural of game' },
      { row: 4, clue: 'A narrow stream of water' },
    ],
    down: { col: 2, word: 'FLAME', clue: 'The glowing part of fire 🔥' },
  },
  {
    id: 6, theme: '🌍 Earth',
    grid: [
      ['P','O','W','E','R'],
      ['B','R','O','O','K'],
      ['F','O','R','C','E'],
      ['C','O','L','O','R'],
      ['B','U','D','D','Y'],
    ],
    across: [
      { row: 0, clue: 'Strength or energy' },
      { row: 1, clue: 'A small gentle stream' },
      { row: 2, clue: 'A push or physical strength' },
      { row: 3, clue: 'A hue or shade (US spelling)' },
      { row: 4, clue: 'A close friend' },
    ],
    down: { col: 2, word: 'WORLD', clue: 'Planet Earth and everything on it 🌍' },
  },
  {
    id: 7, theme: '🎵 Music',
    grid: [
      ['T','I','M','E','R'],
      ['T','R','U','T','H'],
      ['T','A','S','T','E'],
      ['T','H','I','R','D'],
      ['G','E','C','K','O'],
    ],
    across: [
      { row: 0, clue: 'Device that counts down seconds' },
      { row: 1, clue: 'The opposite of a lie' },
      { row: 2, clue: 'One of the five senses' },
      { row: 3, clue: 'Position number three' },
      { row: 4, clue: 'Small wall-climbing lizard 🦎' },
    ],
    down: { col: 2, word: 'MUSIC', clue: 'Sound organised into melody 🎵' },
  },
  {
    id: 8, theme: '☀️ Solar',
    grid: [
      ['B','I','S','O','N'],
      ['F','L','O','O','R'],
      ['H','E','L','L','O'],
      ['B','O','A','R','D'],
      ['H','U','R','R','Y'],
    ],
    across: [
      { row: 0, clue: 'Large shaggy North American buffalo' },
      { row: 1, clue: 'The ground surface of a room' },
      { row: 2, clue: 'A friendly greeting' },
      { row: 3, clue: 'A flat piece of wood or card' },
      { row: 4, clue: 'To move very quickly; rush' },
    ],
    down: { col: 2, word: 'SOLAR', clue: 'Relating to the Sun ☀️' },
  },
  {
    id: 9, theme: '💃 Dance',
    grid: [
      ['H','E','D','G','E'],
      ['B','E','A','C','H'],
      ['B','O','N','U','S'],
      ['R','O','C','K','Y'],
      ['W','H','E','E','L'],
    ],
    across: [
      { row: 0, clue: 'A boundary of bushes or shrubs' },
      { row: 1, clue: 'Sandy shore by the sea 🏖️' },
      { row: 2, clue: 'An extra reward or payment' },
      { row: 3, clue: 'Full of rocks; rough terrain' },
      { row: 4, clue: 'A circular rolling object' },
    ],
    down: { col: 2, word: 'DANCE', clue: 'Move rhythmically to music 💃' },
  },
  {
    id: 10, theme: '🌎 Earth Science',
    grid: [
      ['T','W','E','E','T'],
      ['T','O','A','S','T'],
      ['N','E','R','V','E'],
      ['W','A','T','C','H'],
      ['U','S','H','E','R'],
    ],
    across: [
      { row: 0, clue: 'A bird sound; a social media post 🐦' },
      { row: 1, clue: 'Grilled bread, often with butter' },
      { row: 2, clue: 'Courage; also carries signals in body' },
      { row: 3, clue: 'A timepiece worn on wrist' },
      { row: 4, clue: 'Someone who guides you to a seat' },
    ],
    down: { col: 2, word: 'EARTH', clue: 'Our home planet 🌎' },
  },
  {
    id: 11, theme: '🦁 Courage',
    grid: [
      ['C','A','B','I','N'],
      ['T','A','R','D','Y'],
      ['F','L','A','R','E'],
      ['N','E','V','E','R'],
      ['S','P','E','E','D'],
    ],
    across: [
      { row: 0, clue: 'Small wooden house in the woods' },
      { row: 1, clue: 'Late; not on time' },
      { row: 2, clue: 'A sudden burst of bright light' },
      { row: 3, clue: 'Not at any time; not ever' },
      { row: 4, clue: 'How fast something moves' },
    ],
    down: { col: 2, word: 'BRAVE', clue: 'Fearless and courageous 🦁' },
  },
  {
    id: 12, theme: '🌙 Night',
    grid: [
      ['P','A','N','I','C'],
      ['T','R','I','B','E'],
      ['S','U','G','A','R'],
      ['A','S','H','E','S'],
      ['E','N','T','R','Y'],
    ],
    across: [
      { row: 0, clue: 'Sudden overwhelming fear' },
      { row: 1, clue: 'A group or community of people' },
      { row: 2, clue: 'Sweet white powder in baking 🍰' },
      { row: 3, clue: 'What remains after something burns' },
      { row: 4, clue: 'A way in; an entrance' },
    ],
    down: { col: 2, word: 'NIGHT', clue: 'Dark hours after sunset 🌙' },
  },
]
