import { useState,type FormEvent } from 'react';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { Link,useNavigate,useSearchParams } from 'react-router-dom';
import { api,apiBase } from './api';
import { toast } from 'sonner';
export default function Account(){
 const [signup,setSignup]=useState(false),nav=useNavigate(),client=useQueryClient(),[params]=useSearchParams();
 const {data:providers}=useQuery({queryKey:['providers'],queryFn:()=>api<{google:boolean}>('/auth/providers')});
 const mutation=useMutation({mutationFn:(body:Record<string,string>)=>api(signup?'/auth/register':'/auth/login',body),onSuccess:async()=>{await client.invalidateQueries({queryKey:['me']});toast.success(signup?'Welcome to Arcadia.':'Welcome back.');nav('/profile');}});
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget)) as Record<string,string>;mutation.mutate(data);}
 return <main><Link className="back" to="/">← Back to arcade</Link><section className="surface auth"><p className="eyebrow">YOUR NEXT CHAPTER</p><h1>{signup?'Join the arcade.':'Welcome back.'}</h1><p>Save your progress. Challenge a friend. Make your mark.</p><form className="stack" onSubmit={submit}>{signup&&<label>Player name<input name="username" autoComplete="nickname" required minLength={3} maxLength={24} pattern="[a-zA-Z0-9_]+" title="3–24 letters, numbers or underscores"/></label>}<label>Email<input type="email" name="email" autoComplete="email" required maxLength={254}/></label><label>Password<input type="password" name="password" autoComplete={signup?'new-password':'current-password'} minLength={12} maxLength={128} required/></label><small className="muted">Use at least 12 characters.</small>{mutation.error&&<p role="alert" className="error">{mutation.error.message}</p>}{params.has('error')&&<p role="alert">This email already has a password account. Sign in with your password.</p>}<button className="primary" disabled={mutation.isPending}>{mutation.isPending?'Connecting…':signup?'Create account':'Sign in'}</button></form>{providers?.google&&<a className="google-button" href={`${apiBase}/api/auth/google`}>Continue with Google</a>}<button className="text-button" onClick={()=>{setSignup(!signup);mutation.reset();}}>{signup?'Already a player? Sign in':'New here? Create an account'}</button><Link className="text-button" to="/">Keep playing as a guest →</Link></section></main>;
}
