import { lazy,Suspense,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { useProfile } from './api';
const Snake=lazy(()=>import('./games/Snake'));
const Pong=lazy(()=>import('./games/Pong'));
export default function Game(){
 const {gameId}=useParams(),[playing,setPlaying]=useState(false),[online,setOnline]=useState(false),[run,setRun]=useState(0),{data:user}=useProfile();
 if(gameId!=='snake'&&gameId!=='pong')return <main><h1>Game not found.</h1><Link to="/">Back to arcade</Link></main>;
 const snake=gameId==='snake';
 return <main><Link className="back" to="/">← Back to arcade</Link><p className="eyebrow">{snake?'THE CLASSIC, REMIXED':'FIRST TO SEVEN'}</p><h1>{snake?'Snake Evolved':'Pong After Hours'}<span>.</span></h1>{playing?<><div className="row" style={{marginTop:20}}><button onClick={()=>{setPlaying(false);setRun(r=>r+1);}}>Leave game</button></div><Suspense fallback={<div className="skeleton"/>}>{snake?<Snake key={run}/>:<Pong key={run} online={online}/>}</Suspense></>:<div className="lobby-grid"><section className="surface"><h2>{snake?'A familiar game. A few new twists.':'Keep the rally alive.'}</h2><p>{snake?'Collect food, weave around obstacles, and make every second count. You have 60 seconds.':'Move your paddle to return the ball. Angled hits change its direction, and every rally gets faster. First to seven wins; matches stop after five minutes.'}</p><ul>{snake?<><li>Arrow keys, WASD, or touch controls to steer.</li><li>Purple power-ups let you wrap through walls for 6 seconds.</li><li>Orange boosts increase speed and double food points for 5 seconds.</li><li>Walls, obstacles, and your own body end the run.</li></>:<><li>Move your pointer or touch the court to aim.</li><li>Arrow keys or W / S also move your paddle.</li><li>Play the AI, or invite a friend with a room code.</li><li>Online games use server-controlled scores.</li></>}</ul>{!snake&&<div className="mode-picker"><button className={!online?'active':''} onClick={()=>setOnline(false)}>Practice vs AI</button><button className={online?'active':''} onClick={()=>setOnline(true)}>Online duel</button></div>}{online&&!user?<Link className="primary" to="/login">Sign in for online play</Link>:<button className="primary" onClick={()=>setPlaying(true)}>Play now ↗</button>}</section><section className="surface"><p className="eyebrow">MAKE IT YOUR NEXT BEST</p><h2>{snake?'Chase your own high score.':'Bring a worthy opponent.'}</h2><p>{snake?'Practice progress is saved on this device and synced to your account when connected.':'Completed online duels earn account XP and leaderboard points. Practice matches are saved separately.'}</p><Link to={snake?'/profile':'/leaderboard'} className="primary">{snake?'View my activity':'See high scores'} ↗</Link><p className="muted">{snake?'Local best: '+Math.max(0,...readBest()):'Live rankings · Top 100'}</p></section></div>}</main>;
}
function readBest(){try{return JSON.parse(localStorage.getItem('arcadia-progress-v1')??'{}').state?.history?.filter((r:{game:string})=>r.game==='snake').map((r:{score:number})=>r.score)??[];}catch{return [];}}
