import { useQuery,useMutation,useQueryClient } from '@tanstack/react-query';
import { Link,useNavigate } from 'react-router-dom';
import { ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip } from 'recharts';
import type { Match } from '@arcadia/shared';
import { api,useProfile } from './api';
import { useLocal } from './state';
export default function Profile(){
 const {data:user,isLoading}=useProfile(),local=useLocal(s=>s.history),client=useQueryClient(),nav=useNavigate();
 const history=useQuery({queryKey:['matches',user?.id],queryFn:()=>api<Match[]>('/matches'),enabled:!!user});
 const logout=useMutation({mutationFn:()=>api('/auth/logout',{},'POST'),onSuccess:()=>{client.removeQueries({queryKey:['matches']});client.setQueryData(['me'],null);nav('/');}});
 const rows=user?(history.data??local.filter(r=>r.owner===user.id)):local.filter(r=>!r.owner);
 return <main><p className="eyebrow">MY ACTIVITY</p><h1>{isLoading?'Loading profile…':user?`Good game, ${user.username}.`:'Every round counts.'}</h1><p className="muted">{user?'Your latest 100 matches and account progress.':'Guest progress stays on this device. Sign in to save future rounds.'}</p><div className="row">{user?<button onClick={()=>logout.mutate()} disabled={logout.isPending}>Sign out</button>:<Link className="primary" to="/login">Sign in</Link>}{logout.error&&<p role="alert">{logout.error.message}</p>}</div><div className="stats"><div className="surface"><span className="muted">{user?'Account XP':'Practice XP'}</span><strong>{user?.xp??rows.length*10}</strong></div><div className="surface"><span className="muted">Level</span><strong>{1+Math.floor((user?.xp??rows.length*10)/100)}</strong></div><div className="surface"><span className="muted">Login streak</span><strong>{user?.streak??0}<small> days</small></strong></div></div><section className="surface"><h2>Recent scores</h2>{rows.length?<div style={{height:220}}><ResponsiveContainer><AreaChart data={[...rows].reverse().map((r,i)=>({...r,round:i+1}))}><XAxis dataKey="round"/><YAxis/><Tooltip/><Area type="monotone" dataKey="score" stroke="#85b82c" fill="#85b82c" fillOpacity={0.15}/></AreaChart></ResponsiveContainer></div>:<p>Your first round starts the story. <Link to="/">Pick a game →</Link></p>}</section><section className="surface"><h2>Match history</h2>{history.isError&&<p role="alert">Cloud history is unavailable. Showing locally saved rounds. <button onClick={()=>history.refetch()}>Retry</button></p>}<div className="table-scroll"><table><thead><tr><th>Game</th><th>Score</th><th>Duration</th><th>Opponent / mode</th><th>Played</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.game}</td><td>{r.score}</td><td>{r.duration}s</td><td>{'opponent' in r&&r.opponent?r.opponent:'Practice · unranked'}</td><td>{new Date(r.playedAt).toLocaleDateString()}</td></tr>)}</tbody></table></div></section></main>;
}
