// difficulty: 'easy' | 'medium' | 'hard'
export const COUNTRIES = [
  // Easy — well-known worldwide
  { flag: '🇺🇸', name: 'United States',    difficulty: 'easy' },
  { flag: '🇬🇧', name: 'United Kingdom',   difficulty: 'easy' },
  { flag: '🇫🇷', name: 'France',           difficulty: 'easy' },
  { flag: '🇩🇪', name: 'Germany',          difficulty: 'easy' },
  { flag: '🇮🇹', name: 'Italy',            difficulty: 'easy' },
  { flag: '🇯🇵', name: 'Japan',            difficulty: 'easy' },
  { flag: '🇨🇳', name: 'China',            difficulty: 'easy' },
  { flag: '🇮🇳', name: 'India',            difficulty: 'easy' },
  { flag: '🇧🇷', name: 'Brazil',           difficulty: 'easy' },
  { flag: '🇦🇺', name: 'Australia',        difficulty: 'easy' },
  { flag: '🇨🇦', name: 'Canada',           difficulty: 'easy' },
  { flag: '🇷🇺', name: 'Russia',           difficulty: 'easy' },
  { flag: '🇲🇽', name: 'Mexico',           difficulty: 'easy' },
  { flag: '🇰🇷', name: 'South Korea',      difficulty: 'easy' },
  { flag: '🇦🇷', name: 'Argentina',        difficulty: 'easy' },
  { flag: '🇪🇸', name: 'Spain',            difficulty: 'easy' },
  { flag: '🇵🇹', name: 'Portugal',         difficulty: 'easy' },
  { flag: '🇳🇱', name: 'Netherlands',      difficulty: 'easy' },
  { flag: '🇸🇪', name: 'Sweden',           difficulty: 'easy' },
  { flag: '🇿🇦', name: 'South Africa',     difficulty: 'easy' },
  { flag: '🇳🇬', name: 'Nigeria',          difficulty: 'easy' },
  { flag: '🇪🇬', name: 'Egypt',            difficulty: 'easy' },
  { flag: '🇹🇷', name: 'Turkey',           difficulty: 'easy' },
  { flag: '🇸🇦', name: 'Saudi Arabia',     difficulty: 'easy' },
  { flag: '🇬🇷', name: 'Greece',           difficulty: 'easy' },
  { flag: '🇳🇴', name: 'Norway',           difficulty: 'easy' },
  { flag: '🇩🇰', name: 'Denmark',          difficulty: 'easy' },
  { flag: '🇫🇮', name: 'Finland',          difficulty: 'easy' },
  { flag: '🇵🇱', name: 'Poland',           difficulty: 'easy' },
  { flag: '🇺🇦', name: 'Ukraine',          difficulty: 'easy' },

  // Medium — recognisable but less famous
  { flag: '🇮🇩', name: 'Indonesia',        difficulty: 'medium' },
  { flag: '🇵🇰', name: 'Pakistan',         difficulty: 'medium' },
  { flag: '🇧🇩', name: 'Bangladesh',       difficulty: 'medium' },
  { flag: '🇻🇳', name: 'Vietnam',          difficulty: 'medium' },
  { flag: '🇵🇭', name: 'Philippines',      difficulty: 'medium' },
  { flag: '🇹🇭', name: 'Thailand',         difficulty: 'medium' },
  { flag: '🇲🇾', name: 'Malaysia',         difficulty: 'medium' },
  { flag: '🇸🇬', name: 'Singapore',        difficulty: 'medium' },
  { flag: '🇮🇱', name: 'Israel',           difficulty: 'medium' },
  { flag: '🇮🇷', name: 'Iran',             difficulty: 'medium' },
  { flag: '🇰🇪', name: 'Kenya',            difficulty: 'medium' },
  { flag: '🇬🇭', name: 'Ghana',            difficulty: 'medium' },
  { flag: '🇪🇹', name: 'Ethiopia',         difficulty: 'medium' },
  { flag: '🇹🇿', name: 'Tanzania',         difficulty: 'medium' },
  { flag: '🇨🇴', name: 'Colombia',         difficulty: 'medium' },
  { flag: '🇨🇱', name: 'Chile',            difficulty: 'medium' },
  { flag: '🇵🇪', name: 'Peru',             difficulty: 'medium' },
  { flag: '🇻🇪', name: 'Venezuela',        difficulty: 'medium' },
  { flag: '🇪🇨', name: 'Ecuador',          difficulty: 'medium' },
  { flag: '🇧🇴', name: 'Bolivia',          difficulty: 'medium' },
  { flag: '🇵🇾', name: 'Paraguay',         difficulty: 'medium' },
  { flag: '🇺🇾', name: 'Uruguay',          difficulty: 'medium' },
  { flag: '🇨🇿', name: 'Czech Republic',   difficulty: 'medium' },
  { flag: '🇭🇺', name: 'Hungary',          difficulty: 'medium' },
  { flag: '🇷🇴', name: 'Romania',          difficulty: 'medium' },
  { flag: '🇧🇪', name: 'Belgium',          difficulty: 'medium' },
  { flag: '🇨🇭', name: 'Switzerland',      difficulty: 'medium' },
  { flag: '🇦🇹', name: 'Austria',          difficulty: 'medium' },
  { flag: '🇮🇶', name: 'Iraq',             difficulty: 'medium' },
  { flag: '🇯🇴', name: 'Jordan',           difficulty: 'medium' },
  { flag: '🇲🇦', name: 'Morocco',          difficulty: 'medium' },
  { flag: '🇩🇿', name: 'Algeria',          difficulty: 'medium' },
  { flag: '🇹🇳', name: 'Tunisia',          difficulty: 'medium' },
  { flag: '🇨🇺', name: 'Cuba',             difficulty: 'medium' },
  { flag: '🇯🇲', name: 'Jamaica',          difficulty: 'medium' },
  { flag: '🇿🇼', name: 'Zimbabwe',         difficulty: 'medium' },
  { flag: '🇿🇲', name: 'Zambia',           difficulty: 'medium' },
  { flag: '🇺🇬', name: 'Uganda',           difficulty: 'medium' },
  { flag: '🇷🇼', name: 'Rwanda',           difficulty: 'medium' },
  { flag: '🇨🇲', name: 'Cameroon',         difficulty: 'medium' },

  // Hard — less commonly known flags
  { flag: '🇸🇰', name: 'Slovakia',         difficulty: 'hard' },
  { flag: '🇸🇮', name: 'Slovenia',         difficulty: 'hard' },
  { flag: '🇭🇷', name: 'Croatia',          difficulty: 'hard' },
  { flag: '🇷🇸', name: 'Serbia',           difficulty: 'hard' },
  { flag: '🇦🇱', name: 'Albania',          difficulty: 'hard' },
  { flag: '🇲🇪', name: 'Montenegro',       difficulty: 'hard' },
  { flag: '🇧🇦', name: 'Bosnia & Herz.',   difficulty: 'hard' },
  { flag: '🇲🇰', name: 'North Macedonia',  difficulty: 'hard' },
  { flag: '🇱🇹', name: 'Lithuania',        difficulty: 'hard' },
  { flag: '🇱🇻', name: 'Latvia',           difficulty: 'hard' },
  { flag: '🇪🇪', name: 'Estonia',          difficulty: 'hard' },
  { flag: '🇧🇬', name: 'Bulgaria',         difficulty: 'hard' },
  { flag: '🇨🇾', name: 'Cyprus',           difficulty: 'hard' },
  { flag: '🇲🇹', name: 'Malta',            difficulty: 'hard' },
  { flag: '🇱🇺', name: 'Luxembourg',       difficulty: 'hard' },
  { flag: '🇮🇸', name: 'Iceland',          difficulty: 'hard' },
  { flag: '🇲🇩', name: 'Moldova',          difficulty: 'hard' },
  { flag: '🇧🇾', name: 'Belarus',          difficulty: 'hard' },
  { flag: '🇦🇿', name: 'Azerbaijan',       difficulty: 'hard' },
  { flag: '🇦🇲', name: 'Armenia',          difficulty: 'hard' },
  { flag: '🇬🇪', name: 'Georgia',          difficulty: 'hard' },
  { flag: '🇰🇿', name: 'Kazakhstan',       difficulty: 'hard' },
  { flag: '🇺🇿', name: 'Uzbekistan',       difficulty: 'hard' },
  { flag: '🇲🇳', name: 'Mongolia',         difficulty: 'hard' },
  { flag: '🇳🇵', name: 'Nepal',            difficulty: 'hard' },
  { flag: '🇱🇰', name: 'Sri Lanka',        difficulty: 'hard' },
  { flag: '🇰🇭', name: 'Cambodia',         difficulty: 'hard' },
  { flag: '🇲🇲', name: 'Myanmar',          difficulty: 'hard' },
  { flag: '🇱🇦', name: 'Laos',             difficulty: 'hard' },
  { flag: '🇫🇯', name: 'Fiji',             difficulty: 'hard' },
  { flag: '🇵🇬', name: 'Papua New Guinea', difficulty: 'hard' },
  { flag: '🇸🇳', name: 'Senegal',          difficulty: 'hard' },
  { flag: '🇲🇱', name: 'Mali',             difficulty: 'hard' },
  { flag: '🇨🇮', name: "Côte d'Ivoire",    difficulty: 'hard' },
  { flag: '🇧🇫', name: 'Burkina Faso',     difficulty: 'hard' },
  { flag: '🇳🇪', name: 'Niger',            difficulty: 'hard' },
  { flag: '🇹🇩', name: 'Chad',             difficulty: 'hard' },
  { flag: '🇦🇴', name: 'Angola',           difficulty: 'hard' },
  { flag: '🇳🇦', name: 'Namibia',          difficulty: 'hard' },
  { flag: '🇲🇿', name: 'Mozambique',       difficulty: 'hard' },
  { flag: '🇲🇬', name: 'Madagascar',       difficulty: 'hard' },
  { flag: '🇸🇸', name: 'South Sudan',      difficulty: 'hard' },
  { flag: '🇸🇴', name: 'Somalia',          difficulty: 'hard' },
  { flag: '🇩🇯', name: 'Djibouti',         difficulty: 'hard' },
  { flag: '🇪🇷', name: 'Eritrea',          difficulty: 'hard' },
  { flag: '🇨🇻', name: 'Cape Verde',       difficulty: 'hard' },
  { flag: '🇲🇺', name: 'Mauritius',        difficulty: 'hard' },
  { flag: '🇸🇨', name: 'Seychelles',       difficulty: 'hard' },
  { flag: '🇧🇼', name: 'Botswana',         difficulty: 'hard' },
  { flag: '🇱🇸', name: 'Lesotho',          difficulty: 'hard' },
]

export const POINTS = { easy: 10, medium: 20, hard: 35 }
