import { useEffect,useRef,useState } from 'react';
import { SnakeEngine,type Direction } from '@arcadia/engine';
import { useResult } from './useResult';
export default function Snake(){
 const canvas=useRef<HTMLCanvasElement>(null),engine=useRef(new SnakeEngine()),save=useResult('snake'),saveRef=useRef(save),[view,setView]=useState({score:0,time:60,over:false,ghost:false,boost:false}),[paused,setPaused]=useState(false),pauseRef=useRef(false);
 saveRef.current=save;
 useEffect(()=>{pauseRef.current=paused;},[paused]);
 useEffect(()=>{
  let frame=0,last=0;const e=engine.current,ctx=canvas.current!.getContext('2d')!;
  const key=(ev:KeyboardEvent)=>{const map:Record<string,Direction>={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};if(map[ev.key]){ev.preventDefault();e.turn(map[ev.key]);}if(ev.code==='Space'){ev.preventDefault();setPaused(v=>!v);}};
  const visibility=()=>{if(document.hidden)setPaused(true);};
  const draw=(now:number)=>{if(last&&!pauseRef.current)e.update(now-last);last=now;ctx.fillStyle='#10170e';ctx.fillRect(0,0,500,500);ctx.strokeStyle='#1d2b17';ctx.lineWidth=1;for(let i=0;i<=20;i++){ctx.beginPath();ctx.moveTo(i*25,0);ctx.lineTo(i*25,500);ctx.moveTo(0,i*25);ctx.lineTo(500,i*25);ctx.stroke();}const cell=(x:number,y:number,color:string)=>{ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x*25+2,y*25+2,21,21,5);ctx.fill();};e.obstacles.forEach(p=>cell(p.x,p.y,'#536047'));e.snake.forEach((p,i)=>cell(p.x,p.y,e.ghost?'#c7a4f6':i===0?'#e2ff9c':'#9bc850'));cell(e.food.x,e.food.y,'#ff9973');if(e.power)cell(e.power.x,e.power.y,e.power.kind==='ghost'?'#c7a4f6':'#ffbe4f');setView({score:e.score,time:Math.ceil((60000-e.elapsed)/1000),over:e.over,ghost:e.ghost,boost:e.boost});if(e.over){saveRef.current(e.score,e.elapsed/1000);return;}frame=requestAnimationFrame(draw);};
  window.addEventListener('keydown',key);document.addEventListener('visibilitychange',visibility);frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',key);document.removeEventListener('visibilitychange',visibility);};
 },[]);
 const start=useRef<{x:number;y:number}|null>(null);
 return <section className="game-stage" style={{maxWidth:500}}><div className="scorebar"><strong>Score {view.score}</strong><span>{view.time}s remaining</span><button onClick={()=>setPaused(!paused)} disabled={view.over}>{paused?'Resume':'Pause'}</button></div><p className="game-status muted" role="status">{view.over?'Run complete.':paused?'Paused — resume when ready.':view.ghost?'Ghost mode active':view.boost?'Speed boost · 2× points':'Collect food. Keep moving.'}</p><canvas ref={canvas} width={500} height={500} aria-label="Snake game board. Use arrow keys or the direction buttons to steer." onPointerDown={ev=>{start.current={x:ev.clientX,y:ev.clientY};ev.currentTarget.setPointerCapture(ev.pointerId);}} onPointerUp={ev=>{if(!start.current)return;const dx=ev.clientX-start.current.x,dy=ev.clientY-start.current.y;if(Math.max(Math.abs(dx),Math.abs(dy))>10)engine.current.turn(Math.abs(dx)>Math.abs(dy)?dx>0?'right':'left':dy>0?'down':'up');start.current=null;}}/>{!view.over?<div className="controls">{(['left','up','down','right'] as Direction[]).map((dir,i)=><button key={dir} aria-label={`Move ${dir}`} onClick={()=>engine.current.turn(dir)}>{['←','↑','↓','→'][i]}</button>)}</div>:<div className="surface" role="status"><h2>Nice run.</h2><div className="result-title">{view.score}<small> points</small></div><p>Saved as unranked practice. Leave the game to start another round.</p></div>}</section>;
}
